nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.6.4.cjs

npmRegistries:
  "PRIVATE_REGISTRY_ADDRESS":
    npmAlwaysAuth: true
    npmAuthToken: "YOUR_TOKEN"
npmScopes:
  "aww-vzc":
    npmAlwaysAuth: true
    npmRegistryServer: "PRIVATE_REGISTRY_ADDRESS"

packageExtensions:
  "follow-redirects@*":
    dependencies:
      debug: "*"
  "debug@*":
    dependencies:
      supports-color: "*"
